### ISSUE TITLE
Calva support for YAMLScript in VS Code

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yamlscript#111]
We need support for YAMLScript in VS Code and [Calva](https://github.com/BetterThanTomorrow/calva) is the way to go.

I think the way to do it to first support source mapping in the YS compiler. 
That links every position in the generated Clojure back to a position in YS file being edited.

That way we can use everything Calva does with Clojure but map it back to the YS file in the editor.

I need to work through the details with @PEZ the Calva author.

**Comment by riotrah** [comment]
I would be interested to know what sort of support and features you had in mind

**Comment by ingydotnet** [comment]
@PEZ and I need to have a discussion first.

**Comment by ingydotnet** [comment]
Archived for later
