### ISSUE TITLE
Perl binding should install deps as part of build process

### ISSUE THREAD

**Issue by xanni** [yaml/yamlscript#178]
I can't run the Perl tests without first manually installing the FFI::CheckLib and FFI::Platypus packages.

**Comment by ingydotnet** [comment]
We'll skip Perl actions unless perl and cpanm are installed.
Otherwise we'll locallib install all deps with cpanm.

**Comment by ingydotnet** [comment]
Fixed in 8db8f83f79868f4e4b1e9f218b27131c86f4ff8c
