### ISSUE TITLE
Chained merges `<<:` don’t work

### ISSUE THREAD

**Issue by danielbayley** [yaml/yamlscript#197]
For example:
~~~ yaml
one: &a
  a: 1

two: &b
  <<: *a
  b: 2

three:
  <<: *b
  c: 3
~~~
should produce:
~~~ json
{
  "one": {
    "a": 1
  },
  "two": {
    "a": 1,
    "b": 2
  },
  "three": {
    "a": 1,
    "b": 2,
    "c": 3
  }
}
~~~
but instead, produces:
~~~ json
{
  "one": {
    "a": 1
  },
  "two": {
    "a": 1,
    "b": 2
  },
  "three": {
    "<<": {
      "a": 1
    },
    "b": 2,
    "c": 3
  }
}
~~~

**Comment by ingydotnet** [comment]
Good catch. Fixed in ffdf7f5f.
Pushed to `devel` branch.
You can install `ys` from that branch with:

```
make install-ys PREFIX=</some/path/with/bin/in/PATH>  # defaults to $HOME/.local
```

Planning to release 0.1.86 tonight. 
Looking at your PR https://github.com/yaml/yamlscript/pull/196 next.

**Comment by ingydotnet** [comment]
Fix ffdf7f5 released in 0.1.86

**Comment by danielbayley** [comment]
Nice one @ingydotnet, one thing remains though—so while this works now:
~~~ yaml
one: &a
  a: 1

two: &b
  <<: *a
  b: 2

three:
  <<: *b
~~~
(although the order of keys is reversed—which is probably be a bug?)
~~~ json
{
  "one": {
    "a": 1
  },
  "two": {
    "b": 2,
    "a": 1
  },
  "three": {
    "c": 3,
    "b": 2,
    "a": 1
  }
}
~~~

This does not:
~~~ yaml
one: &a
  a: 1

two: &b
  <<: *a
  b: 2

three: *b
~~~
~~~ json
{
  "one": {
    "a": 1
  },
  "two": {
    "b": 2,
    "a": 1
  },
  "three": {
    "<<": {
      "a": 1
    },
    "b": 2
  }
}
~~~

**Comment by ingydotnet** [comment]
The key order is right afaik.
It's based on this old thing https://yaml.org/type/merge.html
Which says that you start with the mapping minus the `<<` key, and then add keys from `<<` if they don't exist.

Re the failing case, I suspected that when I fixed it but didn't push past your reported problem because I didn't have the time for it. I will take a look this week.

Please keep the issues coming.

**Comment by ingydotnet** [comment]
Looking at this now.
```
one: &a
  a: 1

two: &b
  <<: *a
  b: 2

three: *b
```
compiles to:
```
{"one" (_& 'a {"a" 1}),
 "two" (+merge (_& 'b {"<<" (_* 'a), "b" 2})),
 "three" (_* 'b)}
```

I need to have the `_*` function look for the merge key and do the merge.

There's a little problem though. At this point we don't know if the key was `<<` `'<<'` or `"<<"`.
The `<<` has to be unquoted to be a YAML merge key.

I have an idea. I'm going to make the compiler produce
```
{"one" (_& 'a {"a" 1}),
 "two" (+merge (_& 'b {:-<< (_* 'a), "b" 2})),
 "three" (_* 'b)}
```

The `:-<<` is a valid Clojure keyword but something that will never show up as a YAML or YS data key.
I'm not even sure keywords make sense at all in data mode, but using a `-` in front just to be safe (in case it makes sense down the road).

**Comment by ingydotnet** [comment]
@danielbayley this is fixed in the `devel` branch now.
I'll likely release this on Sunday, but if you want to test things out you can install easily with: `make install-ys`.
It takes a minute or 2 to compile but doesn't require any deps.

**Comment by ingydotnet** [comment]
44f7fd5 is the fix commit, fwiw.

It was quite a refactoring of how this works but I think it makes it more solid now.

**Comment by ingydotnet** [comment]
Fixed released in 0.1.87

**Comment by danielbayley** [comment]
> Fixed released in 0.1.87

Nice one @ingydotnet! Will check it out…

Although, with Home`brew` being my preferred install method (actually the only method I allow as a strict self-imposed rule for everything on my machine!), I'm wondering if there should be some CI step to automatically bump the [formula](https://github.com/yaml/homebrew-yamlscript/blob/main/ys.rb) version on release?

**Comment by ingydotnet** [comment]
I barely know what I'm doing with homebrew. Any help you can offer would be great.

https://matrix.to/#/@ingy:yaml.io is a good way to chat with me directly if you want...

**Comment by danielbayley** [comment]
> I barely know what I'm doing with homebrew. Any help you can offer would be great.

I can take a look at the setup… As it stands, the `brew-update` util kept failing for me, so I opened https://github.com/yaml/homebrew-yamlscript/pull/1 as a manual update.

> https://matrix.to/#/@ingy:yaml.io is a good way to chat with me directly if you want...

Cool, I'm really hesitant to sign up for yet _another_ account for anything though — according to 1Password I already have well over 400! Trying to cut down…

**Comment by danielbayley** [comment]
> I barely know what I'm doing with homebrew. Any help you can offer would be great.

@ingydotnet Sure, check out #207 and https://github.com/yaml/homebrew-yamlscript/pull/3!
